#! /usr/bin/env sh

# helper functions
check_env() {
  if [ -z ${2+x} ]; then
    echo "Environment variable '$1' is not set."
    exit 1
  fi
}

# Check for required environment variables
check_env "K8S_CA" $K8S_CA
check_env "K8S_API" $K8S_API
check_env "K8S_TKN" $K8S_TKN
check_env "K8S_NS" $K8S_NS

# Set context
printf %s "$K8S_CA" > /root/ca.crt
kubectl config set-cluster deploy-cluster --server=$K8S_API --certificate-authority=/root/ca.crt > /dev/null 2>&1
kubectl config set-credentials deploy-user --token=$K8S_TKN > /dev/null 2>&1
kubectl config set-context deploy --cluster=deploy-cluster --user=deploy-user --namespace=$K8S_NS > /dev/null 2>&1
kubectl config use-context deploy > /dev/null 2>&1

# Test if authentication is successful
RESPONSE=$(kubectl auth can-i create deployment)
if [ "$RESPONSE" == "no" ]; then
  echo "The service account doesn't have permission to deploy."
  exit 1
else
  echo "Ready for deployment, client and server info:"
  kubectl version --short
fi
